frontend/src/search/Search.js

Create very basic search component with no css styling. Styling will be improved and more will be added to this component in future pull requests.

add basic search bar component

---

frontend/src/App.css
frontend/src/map/Map.js
frontend/src/trip-name/TripName.css
frontend/src/trip-name/TripName.js

Implement editable trip name component.
- add Google blue as a variable to App.css
- On click, trip name can be editted and then saved

Trip name component

---

frontend/src/App.js
frontend/src/search/Search.css
frontend/src/search/Search.js

Complete search component with some css styling. Add h1 tag.

Search component

---

frontend/src/navbar/Navbar.js
frontend/src/search/Search.js
frontend/src/search/Search.module.css

Add navbar component with a simple sign in button in the top right corner. Add modular css to search component.

add navbar

---

frontend/src/App.js
frontend/src/route/LocationCard.js
frontend/src/route/LocationCard.module.css
frontend/src/route/OptimizeButton.js
frontend/src/route/OptimizeButton.module.css
frontend/src/trip-name/TripName.js
frontend/src/trip-name/TripName.module.css

- Make all css files module.css
- change css classNames to camelCase
- call styles with `className={styles.[className]}`

Modularize css

---

frontend/src/saved-trips/SavedTrip.js
frontend/src/saved-trips/SavedTrips.css
frontend/src/saved-trips/SavedTrips.js
frontend/src/saved-trips/SavedTrips.module.css

Create list of saved trips with name and edit and share button.

add list of saved trips

---

frontend/src/RouteView.module.css
frontend/src/attraction/Attraction.js
frontend/src/map/Map.module.css
frontend/src/route/Route.js
frontend/src/search/Search.js
frontend/src/trip-name/TripName.js
frontend/src/trip-name/TripName.module.css
package-lock.json

Add alt tag to get rid of warning, implement functionality upon pressing enter on search bar, improve route view css

Clean prototype

---

frontend/src/App.js
frontend/src/navbar/Navbar.js

The `Switch` was imported incorrectly, and the `Router` should surround everything in the app you want to have context from.

Resolve Router issues from renamed import and invalid scoping.

---

frontend/src/saved-trips/SavedTrip.js
frontend/src/saved-trips/SavedTrips.js

When user clicks on saved trip, navigate to the route view of the trip.
For MVP purposes, only use index of the trip until database is created.

add navigation link to saved trip

---

.github/workflows/lint.yml
backend/src/main/java/com/google/sps/servlets/DataServlet.java
frontend/src/RouteView.js

Run `mvn package` on push to github. Goal is to verify that the Java code compiles.
Tested with commit 6552066: https://github.com/googleinterns/step88-2020/runs/846066529

Github CI compiles backend Maven build.

---

backend/pom.xml
backend/src/main/java/com/google/sps/servlets/OptimizeServlet.java
frontend/src/RouteView.js
frontend/src/map/Map.js

- Call distance matrix API
- origins and destinations are both the list of attractions 
- create a dictionary mapping two places to the distance between them
- connect to `\optimize` endpoint, which would call the optimization algorithm

Distance matrix api

---

backend/src/main/java/com/google/sps/servlets/OptimizeServlet.java
frontend/src/RouteView.js
frontend/src/route/Route.js
frontend/src/route/mockData.js

Re-enable `Save` and `Optimize` buttons whenever the user manually changes route ordering. The TSP optimization algorithm is only called once per page refresh, since the optimal order is saved as a state variable.

re enable optimize/save buttons

---

backend/src/main/java/com/google/sps/servlets/AuthServlet.java
frontend/src/App.js
frontend/src/attractions-panel/AttractionsPanel.js

Add redirect url to authentication so that when user logs in on a page they are redirected to the same page upon successful login or logout. 
Add index key to attractions panel to remove warning.

Redirect authentication

---

frontend/src/App.js
frontend/src/RouteView.js
frontend/src/navbar/Navbar.js
frontend/src/route/Route.js
frontend/src/route/SaveButton.js
frontend/src/route/SaveButton.module.css

Move save trip button as according to the mockup. Button is positioned absolutely over the navbar but is still part of the RouteView component in order to preserve state. Button is only visible when user is logged in.
If the user is logged in:
If the user is not logged in:

Move save button

---

backend/src/main/java/com/google/sps/Attraction.java
backend/src/main/java/com/google/sps/servlets/OptimizeServlet.java
frontend/src/ExploreView.js
frontend/src/RouteView.js
frontend/src/map/Map.js
frontend/src/route/LocationCard.module.css
frontend/src/route/Route.js

- Send list of attractions to /optimize endpoint to call tsp algorithm
- Use place coordinates to make calls to Distance Matrix API
- change `coordinates` in attraction json to be two different attributes of `lat` and `lng`
- easier to use, since `lat` and `lng` are always accessed separately 
- change `attractionName` to `name`
- less awkward to call `attraction.name`
- backend instance attribute of `Attraction` can be called `name`
- Adjust opacity of overlay on location cards

Connect optimization alg backend

---

frontend/src/RouteView.js
frontend/src/RouteView.module.css
frontend/src/navbar/Navbar.js
frontend/src/navbar/Navbar.module.css
frontend/src/route/SaveShareButtons.module.css

Move edit button up into navbar, and fix bug that causes clicking anywhere on the navbar to bring you back.

Navbar css

---

frontend/src/ExploreView.js
frontend/src/ExploreView.module.css
frontend/src/map/Map.js
frontend/src/map/Map.module.css

Fix css in map info windows that pop up when the pin is clicked. I had to use inline styles for the css to show up on the map.

map info window styles

---

frontend/src/RouteView.js
frontend/src/RouteView.module.css
frontend/src/map/Map.module.css
frontend/src/route/LocationCard.module.css
frontend/src/route/OptimizeButton.module.css
frontend/src/route/SaveShareButtons.js
frontend/src/trip-name/TripName.js
frontend/src/trip-name/TripName.module.css

Make height of map and route container 70vh so it fits on the screen. Adjust padding and margins as necessary; remove hard coded placeholder text.

style route page

---

frontend/src/ExploreView.module.css

make page responsive

---

frontend/src/App.css
frontend/src/SearchView.js
frontend/src/SearchView.module.css
frontend/src/route/LocationCard.module.css
frontend/src/saved-trips/SavedTrips.module.css
frontend/src/search/Search.js
frontend/src/search/Search.module.css
frontend/src/trip-name/TripName.module.css

- search icon changed to fontawesome icon positioned absolutely on top of search bar 
- add `max-width` to the saved trips 
- add colors as constants in `App.css` so Google colors and gray can be used consistently across the app
- ex: used `color: var(--blue);` to set to color to Google blue

search css

---

frontend/src/App.js
frontend/src/search/Search.js

Encode URI to fix bug that prevented user from logging in on route page. Add id in search component to fix warning.

add encodeURIComponent

---

frontend/src/ExploreView.js
frontend/src/ExploreView.module.css
frontend/src/attraction/Attraction.module.css

Show attraction name when an attraction is hovered or selected
Left: hover
Right: selected

show attraction name on hover/selected

---

frontend/src/map/Map.js

Open only one info window at a time.
- declare `const infowindow = new google.maps.InfoWindow();` outside for loop
- on marker click, close opened infowindow, set content to the attraction related to the marker, open new infowindow

Map pin infowindows

---

frontend/src/ExploreView.js

Add type filter `tourist_attraction` to nearbySearch request

filter by tourist attractions

---

frontend/src/googleApiUtils.js
frontend/src/map/Map.js
frontend/src/search/Search.js
frontend/src/search/Search.module.css

- pass in `mode="search"` into the `Map` in `Search.js` and delete all other props
- implement initial check to return a fragment if `mode === "search"`
- remove `mapContainer` `display: none;` css

remove search onReady function for map

---

frontend/src/RouteView.js
frontend/src/route/OptimizeButton.js
frontend/src/route/OptimizeButton.module.css

Disable the optimze button when algorithm is running and show text "Optimizing"

optimizing disable btn

---

frontend/src/ExploreView.js

Add loading component as specified here: https://react-bootstrap.github.io/components/spinners/#accessibility

add react loading component

---

frontend/src/ExploreView.js
frontend/src/ExploreView.module.css

After the user selects 8 images, make it impossible to select any more, and alert the user.

make number of images over 8 unselectable

---

backend/src/main/java/com/google/sps/servlets/createUserServlet.java
frontend/src/App.js

**What's new:**
Create User Servlet

Create User Servlet

---

frontend/src/ExploreView.module.css
frontend/src/search/Search.module.css

Make explore page more responsive across various screen sizes.

Explore page style
